Added support for using IPA as a TOTP backend.

diff --git a/libexec/actions/generate b/libexec/actions/generate
--- a/libexec/actions/generate
+++ b/libexec/actions/generate
@@ -78,19 +78,46 @@ if [ -z "${flight_MFA_issuer}" ]; then
     exit 1
 fi
 
+flight_MFA_engine=${flight_MFA_engine:-googleauthenticator}
+
 _flightmfa_SECRETFILE="${HOME}/${flight_MFA_secretfile:-.config/flight/mfa.dat}"
+
+_generate_ipa() {
+    local _doc
+    _doc=$(ipa otptoken-add --vendor="${flight_MFA_issuer}" --no-qrcode --all --raw 2>/dev/null)
+    if [ $? -gt 0 ]; then
+	echo "${FLIGHT_PROGRAM_NAME:-mfa}: error: unable to generate OTP token with IPA backend"
+	exit 1
+    fi
+    _flightmfa_URI=$(echo "$_doc" | grep 'uri:' |  awk 'BEGIN { ORS=" " }; {print $2}')
+    _flightmfa_KEY="$(echo "${_flightmfa_URI}" | sed 's/.*secret=\([^&]*\).*/\1/g')"
+    touch "${_flightmfa_SECRETFILE}"
+    chmod 0600 "${_flightmfa_SECRETFILE}"
+    cat <<EOF > "${_flightmfa_SECRETFILE}"
+${_flightmfa_KEY}
+" WINDOW_SIZE 3
+" TOTP_AUTH
+" URI ${_flightmfa_URI}
+EOF
+    chmod 0400 "${_flightmfa_SECRETFILE}"
+}
+
+_generate_googleauthenticator() {
+    google-authenticator -f -u \
+			 -l "${flight_MFA_service}" \
+			 -i "${flight_MFA_issuer}" \
+			 -t -D -e 1 -w 3 -q \
+			 -s "${_flightmfa_SECRETFILE}"
+    _flightmfa_KEY="$(head -n 1 ${_flightmfa_SECRETFILE})"
+    _flightmfa_URI="otpauth://totp/${flight_MFA_service}?secret=${_flightmfa_KEY}&issuer=${flight_MFA_issuer}"
+}
 
 if [ ! -e "${_flightmfa_SECRETFILE}" -o -n "${_flightmfa_FORCE}" ]; then
     _flightmfa_SECRETFILEDIR=$(dirname "${_flightmfa_SECRETFILE}")
     if [ ! -d "${_flightmfa_SECRETFILEDIR}" ]; then
 	mkdir -p "${_flightmfa_SECRETFILEDIR}"
     fi
-    google-authenticator -f -u \
-	-l "${flight_MFA_service}" \
-	-i "${flight_MFA_issuer}" \
-	-t -D -e 1 -w 3 -q \
-	-s "${_flightmfa_SECRETFILE}"
-    _flightmfa_KEY="$(head -n 1 ${_flightmfa_SECRETFILE})"
+    _generate_${flight_MFA_engine}
     if [ "$(tput cols)" -lt 90 ]; then
 	if [ "$(tput cols)" -lt 78 ]; then
 	    echo "WARNING: unable to display QR code (insufficient terminal width)."
@@ -101,7 +128,7 @@ if [ ! -e "${_flightmfa_SECRETFILE}" -o -n "${_flightmfa_FORCE}" ]; then
 	fi
     fi
     qrencode -o - \
-	-t ansi "otpauth://totp/${flight_MFA_service}?secret=${_flightmfa_KEY}&issuer=${flight_MFA_issuer}" \
+	-t ANSIUTF8 "${_flightmfa_URI}" \
 	-m "${_flightmfa_MARGIN:-4}"
     echo "Or use key: ${_flightmfa_KEY}"
 else
